### ISSUE TITLE
Tags are missing for NW.js 0.34.x and 0.35.x builds

### ISSUE THREAD

**Issue by b2ag** [nwjs/chromium.src#132]
While trying to build *FFmpeg* with a script supplied by [nwjs-ffmpeg-prebuilt](https://github.com/iteufel/nwjs-ffmpeg-prebuilt) I've noticed, that tags for this repository stop at *nw-v0.34.0-beta0*. The script is looking for the tag accompanying the newest *NW.js* release *nw-v0.35.5*, but it's missing. Is there another way to find the corresponding *nwjs/chromium.src* version to the latest NW.js release?

**Comment by rogerwang** [comment]
Please check https://github.com/nwjs/nw.js/issues/6864 . Thanks.
