### ISSUE TITLE
Security problem with (I think) the version of Chromium that you use

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [nwjs/chromium.src#142]
Please see here: https://www.linuxcompatible.org/story/serious-security-issue-with-chromium-on-debian/

**Comment by rogerwang** [comment]
Thanks for reporting. But latest NW.js fixed that bug https://nwjs.io/blog/v0.42.2/

**Comment by LinuxOnTheDesktop** [comment]
> latest NW.js fixed that bug

Ah, sorry: my attempt to find the bugtracker for the Chromium-based browser called 'Iridium' ended up, somehow, here on your Issues page. I blame, largely, the Iridium website and how hard it makes to contact the developers of that browser.
