### ISSUE TITLE
@rogerwang i need some historical background from you

### ISSUE THREAD

**Issue by frank-dspeed** [nwjs/chromium.src#157]
Why do we maintain this src repo and not move everything into nwjs/patches is there a reason for that ? else i would start bisecting this and move the patches over so we can more easy sync with electron and chromium it self without maintaining a repo that contains edited source.

please explain your internal workflow so that we can discuess alternatives i want a single source for chromium electron nwjs nodejs. 

If you should not find the time i will simply start the bisect effort and port the patches over and hardfork nwjs as prototype and will create a PR once Electron and Chromium NodeJS are in sync.

**Comment by frank-dspeed** [comment]
@rogerwang input needed asap thanks in advance.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
