### ISSUE TITLE
libvpx not found

### ISSUE THREAD

**Issue by chaseWillden** [nwjs/chromium.src#53]
When running gyp_chromium for nw13, I get the error: 

```
path/to/nwjs/src/third_party/libvpx/libvpx.gyp not found
```
I'm trying to fish through to debug

**Comment by ghostoy** [comment]
Try `gclient sync`.

**Comment by chaseWillden** [comment]
I've been trying that, but no luck.

**Comment by chaseWillden** [comment]
Actually I thought that I had it, but I'm still getting the same error. I've fished through many of the gyp files throughout chromium, but I'm finding nothing referencing third_party/libvpx/libvpx.gyp or anything close. Any ideas on how I can fix this?

**Comment by chaseWillden** [comment]
I only had this issue on my Ubuntu virtual machine. On my Mac, it works find.
