### ISSUE TITLE
BUG: Can't compile out\Debug (nw13)

### ISSUE THREAD

**Issue by ondra-novak** [nwjs/chromium.src#57]
Command
========
ninja -C out\Debug nwjs

Error
=====
[17241/20083] LINK_EMBED payload.exe
FAILED: e:\nwjs\gclient\python276_bin\python.exe gyp-win-tool link-with-manifests environment.x86 True payload.exe "e:\nwjs\gclient\python276_bin\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:payload.exe @payload.exe.rsp" 1 mt.exe rc.exe "obj\chrome\payload.payload.exe.intermediate.manifest" obj\chrome\payload.payload.exe.generated.manifest ..\..\build\win\compatibility.manifest
LIBCMTD.lib(dbgheap.obj) : error LNK2005: __calloc_dbg already defined in allocator.lib(allocator.allocator_shim_win.obj)
LIBCMTD.lib(dbgheap.obj) : error LNK2005: __free_dbg already defined in allocator.lib(allocator.allocator_shim_win.obj)
LIBCMTD.lib(dbgheap.obj) : error LNK2005: __malloc_dbg already defined in allocator.lib(allocator.allocator_shim_win.obj)
LIBCMTD.lib(dbgheap.obj) : error LNK2005: __realloc_dbg already defined in allocator.lib(allocator.allocator_shim_win.obj)
LIBCMTD.lib(dbgheap.obj) : error LNK2005: __recalloc already defined in allocator.lib(allocator.allocator_shim_win.obj)
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
payload.exe : fatal error LNK1169: one or more multiply defined symbols found
Traceback (most recent call last):
  File "gyp-win-tool", line 313, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 169, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "e:\nwjs\gclient\python276_bin\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'e:\nwjs\gclient\python276_bin\python.exe gyp-win-tool link-wrapper environment.x
86 False link.exe /nologo /OUT:payload.exe @payload.exe.rsp payload.exe.manifest.res' returned non-zero exit status 1169

[17241/20083] CXX obj\components\history\core\browser\history_core_browser.history_service.obj
ninja: build stopped: subcommand failed.

Environment:
===========
set DEPOT_TOOLS_WIN_TOOLCHAIN=0
set GYP_MSVS_VERSION=2013
set GYP_DEFINES="clang=0 nwjs_sdk=1 disable_nacl=0"

**Comment by rogerwang** [comment]
Thanks for reporting. Will fix this soon. In the meantime you can use 'chrome' as the build target to workaround 'payload'.
