### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by rajjerry** [nwjs/chromium.src#63]
I want to run this chromium.src using nwjs. how can I run with nwjs. 
Give me a link or something. I create a remote desktop application using chromium code so can you tell me how can i start with nwjs.

**Comment by ghostoy** [comment]
@rajjerry This repo is part of NW.js, which is based on Chromium. So it's composed of multiple repos, including this one, nw.js, v8 and node, as well as many 3rd party dependencies.

If you just want to build a app based on NW.js, please follow our [official document](http://docs.nwjs.io/en/latest/) to get started.

If you want to build your own version of NW.js or contribute to this project, please read [Building NW.js](http://docs.nwjs.io/en/latest/For%20Developers/Building%20NW.js/) and other related documents.
