### ISSUE TITLE
How did you push Chromium to github?

### ISSUE THREAD

**Issue by judax** [nwjs/chromium.src#83]
Hello,

Wanted to contact to ask how you were able to push the whole chromium source folder to github. I am trying to do a similar thing and I am constantly getting:

```
Counting objects: 8369830, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1299652/1299652), done.
remote: fatal: pack exceeds maximum allowed size
fatal: The remote end hung up unexpectedly.00 GiB | 1.31 MiB/s   
fatal: The remote end hung up unexpectedly
```

I know that I should not use issues for a question but I did not know how to contact you otherwise.

Thank you very much in advance.

Regards,
Iker.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
